name: Makefile CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install raylib
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake git libasound2-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libgl1-mesa-dev libxi-dev
        git clone https://github.com/raysan5/raylib.git
        cd raylib
        mkdir build && cd build
        cmake ..
        make -j$(nproc)
        sudo make install

    - name: Build project
      run: make
