name: Makefile CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install raylib
      run: sudo apt update && sudo apt install -y libraylib-dev

    - name: Build project
      run: make
